# Generated by Django 5.2.4 on 2025-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicao', models.CharField(max_length=50)),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_manutencao', models.DateField(blank=True, null=True, verbose_name='Data de Manutenção')),
                ('status', models.CharField(choices=[('Em Uso na Produção', 'Em Uso na Produção'), ('Em Manutenção', 'Em Manutenção'), ('Desativado', 'Desativado')], default='Em Uso na Produção', max_length=20)),
                ('fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal')),
                ('arquivo_nota', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo da Nota (PDF)')),
                ('categoria', models.CharField(choices=[('Equipamento de Produção', 'Equipamento de Produção'), ('Mobiliário', 'Mobiliário'), ('Utensílios', 'Utensílios')], default='Equipamento de Produção', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Patrimônios',
            },
        ),
    ]
