# Generated by Django 5.2.4 on 2025-09-29 17:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('profissional', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
                ('modo_preparo', models.TextField(blank=True, help_text='Digite cada passo do modo de preparo em uma nova linha.')),
                ('rendimento', models.PositiveIntegerField(default=20, help_text='Número de porções')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_por_porcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('kg', 'Kilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=20)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fator_correcao', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receita')),
            ],
            options={
                'verbose_name': 'Item de Receita',
                'verbose_name_plural': 'Itens de Receita',
            },
        ),
    ]
