# Generated by Django 5.2.4 on 2025-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('quantidade_minima', models.PositiveIntegerField(verbose_name='Quantidade Mínima')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('Em Estoque', 'Em Estoque'), ('Em Uso', 'Em Uso'), ('Esgotado', 'Esgotado')], default='Em Estoque', max_length=20)),
                ('fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('numero_nota', models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal')),
                ('arquivo_nota', models.FileField(blank=True, null=True, upload_to='notas_insumos/', verbose_name='Arquivo da Nota (PDF)')),
                ('categoria', models.CharField(choices=[('Embalagem', 'Embalagem'), ('Pacote de Ingrediente', 'Pacote de Ingrediente'), ('Outros', 'Outros')], default='Embalagem', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
            },
        ),
    ]
